\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Práctica 2.},
            pdfauthor={Lisardo Gayán; José Luis Melo},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{Práctica 2.}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{Lisardo Gayán \\ José Luis Melo}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \predate{\centering\large\emph}
  \postdate{\par}
  \date{11 June, 2019}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\section{1 - Descripción del dataset.}\label{descripcion-del-dataset.}

\textbf{¿Por qué es importante y qué pregunta/problema pretende
responder?}

El dataset de Titanic: Machine Learning from Disaster se registran los
datos de los pasajeros del famoso trasatlántico y se utiliza para
predecir los supervivientes. Los datos estan divididos en dos dataset,
uno de test y otro entrenamiento, para la creación de modelos de
predicción.

\section{2 - Integración y selección de los datos de interés a
analizar}\label{integracion-y-seleccion-de-los-datos-de-interes-a-analizar}

Se importan los datos. Primero el dataset train.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datostrain <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./data/train.csv"}\NormalTok{, }\DataTypeTok{stringsAsFactors =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{na.strings =} \KeywordTok{c}\NormalTok{(}\StringTok{"NA"}\NormalTok{, }\StringTok{""}\NormalTok{))}
\KeywordTok{str}\NormalTok{(datostrain)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    891 obs. of  12 variables:
##  $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Survived   : int  0 1 1 1 0 0 0 0 1 1 ...
##  $ Pclass     : int  3 1 3 1 3 3 1 3 3 2 ...
##  $ Name       : chr  "Braund, Mr. Owen Harris" "Cumings, Mrs. John Bradley (Florence Briggs Thayer)" "Heikkinen, Miss. Laina" "Futrelle, Mrs. Jacques Heath (Lily May Peel)" ...
##  $ Sex        : chr  "male" "female" "female" "female" ...
##  $ Age        : num  22 38 26 35 35 NA 54 2 27 14 ...
##  $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
##  $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
##  $ Ticket     : chr  "A/5 21171" "PC 17599" "STON/O2. 3101282" "113803" ...
##  $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
##  $ Cabin      : chr  NA "C85" NA "C123" ...
##  $ Embarked   : chr  "S" "C" "S" "S" ...
\end{verbatim}

Se observa como consta de 891 muestras y 12 variables, entre ellas
Survived.

Posteriormente el dataset test.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datostest <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{ (}\StringTok{"./data/test.csv"}\NormalTok{, }\DataTypeTok{stringsAsFactors =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{na.strings =} \KeywordTok{c}\NormalTok{(}\StringTok{"NA"}\NormalTok{, }\StringTok{""}\NormalTok{))}
\KeywordTok{str}\NormalTok{(datostest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    418 obs. of  11 variables:
##  $ PassengerId: int  892 893 894 895 896 897 898 899 900 901 ...
##  $ Pclass     : int  3 3 2 3 3 3 3 2 3 3 ...
##  $ Name       : chr  "Kelly, Mr. James" "Wilkes, Mrs. James (Ellen Needs)" "Myles, Mr. Thomas Francis" "Wirz, Mr. Albert" ...
##  $ Sex        : chr  "male" "female" "male" "male" ...
##  $ Age        : num  34.5 47 62 27 22 14 30 26 18 21 ...
##  $ SibSp      : int  0 1 0 0 1 0 0 1 0 2 ...
##  $ Parch      : int  0 0 0 0 1 0 0 1 0 0 ...
##  $ Ticket     : chr  "330911" "363272" "240276" "315154" ...
##  $ Fare       : num  7.83 7 9.69 8.66 12.29 ...
##  $ Cabin      : chr  NA NA NA NA ...
##  $ Embarked   : chr  "Q" "S" "Q" "S" ...
\end{verbatim}

Se compone de 418 observaciones y 11 variables. La variable Survived no
aparece debido a que es la que se debe predecir.

A continuacion, a la hora de fusionar los datos caben dos posibilidades,
asignar ``NA'' a la variable datostest\$Survived o no considerar los
datos de survived en train. Se importan, fusionan los datos y se revisa
la estructura inicial de los datos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datostest}\OperatorTok{$}\NormalTok{Survived <-}\StringTok{ }\OtherTok{NA}
\NormalTok{datos <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(datostrain, datostest)}
\KeywordTok{str}\NormalTok{(datos)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1309 obs. of  12 variables:
##  $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Survived   : int  0 1 1 1 0 0 0 0 1 1 ...
##  $ Pclass     : int  3 1 3 1 3 3 1 3 3 2 ...
##  $ Name       : chr  "Braund, Mr. Owen Harris" "Cumings, Mrs. John Bradley (Florence Briggs Thayer)" "Heikkinen, Miss. Laina" "Futrelle, Mrs. Jacques Heath (Lily May Peel)" ...
##  $ Sex        : chr  "male" "female" "female" "female" ...
##  $ Age        : num  22 38 26 35 35 NA 54 2 27 14 ...
##  $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
##  $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
##  $ Ticket     : chr  "A/5 21171" "PC 17599" "STON/O2. 3101282" "113803" ...
##  $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
##  $ Cabin      : chr  NA "C85" NA "C123" ...
##  $ Embarked   : chr  "S" "C" "S" "S" ...
\end{verbatim}

A continuación comprobamos los datos que faltan.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Buscamos primero qué variables tienen valores perdidos}
\NormalTok{missing_numbers <-}\StringTok{ }\KeywordTok{sapply}\NormalTok{(datos, }\ControlFlowTok{function}\NormalTok{(x) \{}\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(x))\})}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Variables =} \KeywordTok{names}\NormalTok{(missing_numbers), }\DataTypeTok{Datos_faltantes=} \KeywordTok{as.vector}\NormalTok{(missing_numbers))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{bootstrap_options =} \StringTok{"striped"}\NormalTok{, }\DataTypeTok{full_width =}\NormalTok{ F, }\DataTypeTok{position =} \StringTok{"left"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|r}
\hline
Variables & Datos\_faltantes\\
\hline
PassengerId & 0\\
\hline
Survived & 418\\
\hline
Pclass & 0\\
\hline
Name & 0\\
\hline
Sex & 0\\
\hline
Age & 263\\
\hline
SibSp & 0\\
\hline
Parch & 0\\
\hline
Ticket & 0\\
\hline
Fare & 1\\
\hline
Cabin & 1014\\
\hline
Embarked & 2\\
\hline
\end{tabular}

Podemos observar, que en Survived, salen los 418, que tenemos que
predecir, por lo que todos los valores de train están informados.

A continuación se detallan las variables y su tipo inicial, este último,
se modificara para su mejor análisis.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# datostrain1 <- datostrain[,-2]}
\CommentTok{# data <- rbind(datostrain1, datostest) # Fusion datasets}
\NormalTok{data <-}\StringTok{ }\NormalTok{datos[,}\OperatorTok{-}\DecValTok{2}\NormalTok{]}
\KeywordTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1309 obs. of  11 variables:
##  $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Pclass     : int  3 1 3 1 3 3 1 3 3 2 ...
##  $ Name       : chr  "Braund, Mr. Owen Harris" "Cumings, Mrs. John Bradley (Florence Briggs Thayer)" "Heikkinen, Miss. Laina" "Futrelle, Mrs. Jacques Heath (Lily May Peel)" ...
##  $ Sex        : chr  "male" "female" "female" "female" ...
##  $ Age        : num  22 38 26 35 35 NA 54 2 27 14 ...
##  $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
##  $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
##  $ Ticket     : chr  "A/5 21171" "PC 17599" "STON/O2. 3101282" "113803" ...
##  $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
##  $ Cabin      : chr  NA "C85" NA "C123" ...
##  $ Embarked   : chr  "S" "C" "S" "S" ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tipos <-}\StringTok{ }\KeywordTok{sapply}\NormalTok{(data, class)}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Variables =} \KeywordTok{names}\NormalTok{(tipos), }\DataTypeTok{Tipo_Variable=} \KeywordTok{as.vector}\NormalTok{(tipos))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{bootstrap_options =} \StringTok{"striped"}\NormalTok{, }\DataTypeTok{full_width =}\NormalTok{ F, }\DataTypeTok{position =} \StringTok{"left"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|l}
\hline
Variables & Tipo\_Variable\\
\hline
PassengerId & integer\\
\hline
Pclass & integer\\
\hline
Name & character\\
\hline
Sex & character\\
\hline
Age & numeric\\
\hline
SibSp & integer\\
\hline
Parch & integer\\
\hline
Ticket & character\\
\hline
Fare & numeric\\
\hline
Cabin & character\\
\hline
Embarked & character\\
\hline
\end{tabular}

Las variables, que no tienen datos faltantes, class y sex, se
convertiran a factor. La variable cabin tiene muchos datos faltantes,
así que en un primer momento no se utilizará.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#data$Age <- as.integer(data$Age)}
\NormalTok{data}\OperatorTok{$}\NormalTok{Pclass <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(data}\OperatorTok{$}\NormalTok{Pclass)}
\NormalTok{data}\OperatorTok{$}\NormalTok{Sex <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(data}\OperatorTok{$}\NormalTok{Sex)}
\CommentTok{#data$Embarked <- as.factor(data$Embarked)}
\CommentTok{#data$Cabin <- as.factor(data$Cabin)}
\NormalTok{tipos_new <-}\StringTok{ }\KeywordTok{sapply}\NormalTok{(data, class)}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Variables =} \KeywordTok{names}\NormalTok{(tipos_new), }\DataTypeTok{Tipo_Variable=} \KeywordTok{as.vector}\NormalTok{(tipos_new))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{bootstrap_options =} \StringTok{"striped"}\NormalTok{, }\DataTypeTok{full_width =}\NormalTok{ F, }\DataTypeTok{position =} \StringTok{"left"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|l}
\hline
Variables & Tipo\_Variable\\
\hline
PassengerId & integer\\
\hline
Pclass & factor\\
\hline
Name & character\\
\hline
Sex & factor\\
\hline
Age & numeric\\
\hline
SibSp & integer\\
\hline
Parch & integer\\
\hline
Ticket & character\\
\hline
Fare & numeric\\
\hline
Cabin & character\\
\hline
Embarked & character\\
\hline
\end{tabular}

Una vez modificadas los tipos de valores se resume que:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   PassengerId   Pclass      Name               Sex           Age       
##  Min.   :   1   1:323   Length:1309        female:466   Min.   : 0.17  
##  1st Qu.: 328   2:277   Class :character   male  :843   1st Qu.:21.00  
##  Median : 655   3:709   Mode  :character                Median :28.00  
##  Mean   : 655                                           Mean   :29.88  
##  3rd Qu.: 982                                           3rd Qu.:39.00  
##  Max.   :1309                                           Max.   :80.00  
##                                                         NA's   :263    
##      SibSp            Parch          Ticket               Fare        
##  Min.   :0.0000   Min.   :0.000   Length:1309        Min.   :  0.000  
##  1st Qu.:0.0000   1st Qu.:0.000   Class :character   1st Qu.:  7.896  
##  Median :0.0000   Median :0.000   Mode  :character   Median : 14.454  
##  Mean   :0.4989   Mean   :0.385                      Mean   : 33.295  
##  3rd Qu.:1.0000   3rd Qu.:0.000                      3rd Qu.: 31.275  
##  Max.   :8.0000   Max.   :9.000                      Max.   :512.329  
##                                                      NA's   :1        
##     Cabin             Embarked        
##  Length:1309        Length:1309       
##  Class :character   Class :character  
##  Mode  :character   Mode  :character  
##                                       
##                                       
##                                       
## 
\end{verbatim}

PassengerId: Variable de tipo entero que contiene el id del pasajero, no
existen valores nulos o perdidos.\\
Pclass: Variable de tipo factor con la categoria asignada al pasajero,
no existen valores nulos o perdidos.\\
Name: Variable de tipo texto con el nombre del pasajero, no existen
valores nulos o perdidos.\\
Sex: Variable de tipo factor con el genero del pasajero (másculino,
femenino), no existen valores nulos o perdidos.\\
Age: Variable de tipo numérico que especifica la edad del pasajero,
\textbf{existen 263 valores nulos.}\\
SibSp: Variable de tipo entero que especifica el numero de
hermanos/esposa abordo, no existen valores nulos o perdidos.\\
Parch: Variable de tipo entero que especifica el numero de padres/hijos
abordo, no existen valores nulos o perdidos.\\
Ticket: Variable de tipo texto que indica el numero de ticket, no
existen valores nulos o perdidos.\\
Fare: Variable de tipo numero que especifica la tarifa pagada,
\textbf{existe 1 valor nulo.}\\
Cabin: Variable de tipo factor donde se especifica la cabina asignada,
\textbf{existen 1014 valores perdidos.}\\
Embarked: Variable de tipo factor que indica el puerto de embarque,
\textbf{existen 2 valores perdidos.}

\section{3 - Limpieza de datos}\label{limpieza-de-datos}

\textbf{3.1. ¿Los datos contienen ceros o elementos vacíos? ¿Cómo
gestionarías cada uno de estos casos?}

Volvemos a mostrar los datos que contienen ceros o elementos vacíos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Busco primero qué variables tienen valores perdidos}
\NormalTok{missing_numbers <-}\StringTok{ }\KeywordTok{sapply}\NormalTok{(datos, }\ControlFlowTok{function}\NormalTok{(x) \{}\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(x))\})}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Variables =} \KeywordTok{names}\NormalTok{(missing_numbers), }
                 \DataTypeTok{Datos_faltantes=} \KeywordTok{as.vector}\NormalTok{(missing_numbers))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{bootstrap_options =} \StringTok{"striped"}\NormalTok{, }\DataTypeTok{full_width =}\NormalTok{ F, }\DataTypeTok{position =} \StringTok{"left"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|r}
\hline
Variables & Datos\_faltantes\\
\hline
PassengerId & 0\\
\hline
Survived & 418\\
\hline
Pclass & 0\\
\hline
Name & 0\\
\hline
Sex & 0\\
\hline
Age & 263\\
\hline
SibSp & 0\\
\hline
Parch & 0\\
\hline
Ticket & 0\\
\hline
Fare & 1\\
\hline
Cabin & 1014\\
\hline
Embarked & 2\\
\hline
\end{tabular}

De las variables existentes a continuación se espedifican aquellas que
contienen valores perdido o nulos.

\begin{itemize}
\tightlist
\item
  Age: \emph{existen 263 valores nulos.}
\end{itemize}

Para imputar valores de \textbf{edad}, se aplicara el algoritmo rpart,
que es un árbol de regresión.

Comprobamos la variable Age

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(data}\OperatorTok{$}\NormalTok{Age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##    0.17   21.00   28.00   29.88   39.00   80.00     263
\end{verbatim}

Se comprueba como hay 263 valores nulos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Referencia: }
\CommentTok{# https://www.rdocumentation.org/packages/rpart/versions/4.1-15/topics/rpart}
\NormalTok{age_model <-}\StringTok{ }\KeywordTok{rpart}\NormalTok{(Age }\OperatorTok{~}\StringTok{ }\NormalTok{Pclass }\OperatorTok{+}\StringTok{ }\NormalTok{Sex }\OperatorTok{+}\StringTok{ }\NormalTok{SibSp }\OperatorTok{+}\StringTok{ }\NormalTok{Parch }\OperatorTok{+}\StringTok{ }\NormalTok{Fare }\OperatorTok{+}\StringTok{ }\NormalTok{Embarked,}
                       \DataTypeTok{data =}\NormalTok{ data[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(data}\OperatorTok{$}\NormalTok{Age),], }\DataTypeTok{method =} \StringTok{"anova"}\NormalTok{)}
\NormalTok{data}\OperatorTok{$}\NormalTok{Age[}\KeywordTok{is.na}\NormalTok{(data}\OperatorTok{$}\NormalTok{Age)] <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(age_model, data[}\KeywordTok{is.na}\NormalTok{(data}\OperatorTok{$}\NormalTok{Age),])}
\KeywordTok{summary}\NormalTok{(data}\OperatorTok{$}\NormalTok{Age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.17   22.00   27.43   29.63   37.00   80.00
\end{verbatim}

También se podrían imputar por otros métodos, como la media, mediana o
mice en lugar del usado rpart.

\begin{itemize}
\tightlist
\item
  Fare: \emph{existe 1 valor nulo.}\\
  Para imputar valores \textbf{Fare}\\
  Dado que unicamente hay un valor perdido, es posible imputarlo por la
  media o la mediana en base al puerto de embarque ``S'' y la clase
  ``3''
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data[}\KeywordTok{is.na}\NormalTok{(data}\OperatorTok{$}\NormalTok{Fare),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      PassengerId Pclass               Name  Sex  Age SibSp Parch Ticket
## 1044        1044      3 Storey, Mr. Thomas male 60.5     0     0   3701
##      Fare Cabin Embarked
## 1044   NA  <NA>        S
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M_fare<-}\StringTok{ }\KeywordTok{subset}\NormalTok{(data,data}\OperatorTok{$}\NormalTok{Pclass }\OperatorTok{==}\StringTok{ '3'} \OperatorTok{&}\StringTok{ }\NormalTok{data}\OperatorTok{$}\NormalTok{Embarked }\OperatorTok{==}\StringTok{ 'S'}\NormalTok{)}
\KeywordTok{mean}\NormalTok{(M_fare}\OperatorTok{$}\NormalTok{Fare, }\DataTypeTok{na.rm =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 14.43542
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{median}\NormalTok{(M_fare}\OperatorTok{$}\NormalTok{Fare, }\DataTypeTok{na.rm =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8.05
\end{verbatim}

Realizamos una gráfica de la distribución de valores de Fare.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(M_fare,  }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Fare)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{fill =} \StringTok{'grey'}\NormalTok{, }\DataTypeTok{alpha=}\FloatTok{0.4}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_vline}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{xintercept=}\KeywordTok{median}\NormalTok{(Fare, }\DataTypeTok{na.rm=}\NormalTok{T)),}
    \DataTypeTok{colour=}\StringTok{'blue'}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{'dashed'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_vline}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{xintercept=}\KeywordTok{mean}\NormalTok{(Fare, }\DataTypeTok{na.rm=}\NormalTok{T)),}
  \DataTypeTok{colour=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{'dashed'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1 rows containing non-finite values (stat_density).
\end{verbatim}

\includegraphics{Practica2_files/figure-latex/Plot nulos Fare-1.pdf}

Observamos como al realizar la gráfica la advertencia \emph{``Removed 1
rows containing non-finite values (stat\_density)''} nos indica que hay
un valor nulo.

La tarifa de 8.05 coincide con la mediana de los pasajeros de tercera
clase que embarcaron en S, por lo que se podría imputar este valor.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\OperatorTok{$}\NormalTok{Fare[}\KeywordTok{c}\NormalTok{(}\DecValTok{1044}\NormalTok{)] <-}\StringTok{ }\FloatTok{8.05}
\NormalTok{data[}\DecValTok{1044}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      PassengerId Pclass               Name  Sex  Age SibSp Parch Ticket
## 1044        1044      3 Storey, Mr. Thomas male 60.5     0     0   3701
##      Fare Cabin Embarked
## 1044 8.05  <NA>        S
\end{verbatim}

Volviendo a representar

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M_fare<-}\StringTok{ }\KeywordTok{subset}\NormalTok{(data,data}\OperatorTok{$}\NormalTok{Pclass }\OperatorTok{==}\StringTok{ '3'} \OperatorTok{&}\StringTok{ }\NormalTok{data}\OperatorTok{$}\NormalTok{Embarked }\OperatorTok{==}\StringTok{ 'S'}\NormalTok{)}
\KeywordTok{ggplot}\NormalTok{(M_fare,  }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Fare)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{fill =} \StringTok{'grey'}\NormalTok{, }\DataTypeTok{alpha=}\FloatTok{0.4}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_vline}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{xintercept=}\KeywordTok{median}\NormalTok{(Fare, }\DataTypeTok{na.rm=}\NormalTok{T)),}
    \DataTypeTok{colour=}\StringTok{'blue'}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{'dashed'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_vline}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{xintercept=}\KeywordTok{mean}\NormalTok{(Fare, }\DataTypeTok{na.rm=}\NormalTok{T)),}
  \DataTypeTok{colour=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{'dashed'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/Plot nulos Fare 2-1.pdf}

Una vez imputado el valor ya no existe advertencia lo que significa que
en Fare ya no hay un valor nulo.

\begin{itemize}
\item
  Cabin: \emph{existen 1014 valores perdidos.}\\
  Para imputar valores \textbf{Cabin}\\
  Esta variable tiene muchos valores perdidos, se podria conseguir
  predecir la cubierta asignada al pasajero pero es un dato que poco
  beneficio podría traer ya que se puede realizar el analisis con la
  combinación entre la tarifa y la clase del pasajero.
\item
  Embarked: \emph{existen 2 valores perdidos.}\\
  Para imputar valores \textbf{Embarked}
\end{itemize}

Mostramos los valores perdidos

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data[}\KeywordTok{is.na}\NormalTok{(data}\OperatorTok{$}\NormalTok{Embarked),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     PassengerId Pclass                                      Name    Sex
## 62           62      1                       Icard, Miss. Amelie female
## 830         830      1 Stone, Mrs. George Nelson (Martha Evelyn) female
##     Age SibSp Parch Ticket Fare Cabin Embarked
## 62   38     0     0 113572   80   B28     <NA>
## 830  62     0     0 113572   80   B28     <NA>
\end{verbatim}

Al ser unicamente dos valores perdidos, se podría sustituir los valores
por la media, en base a otros pasajeros de la misma clase y tarifa
(Fare). Los pasajeros han pagado una tarifa de 80 y pertenecian a
primera clase.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{embarked_pass_}\DecValTok{1}\NormalTok{ <-}\StringTok{ }\NormalTok{data }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(PassengerId }\OperatorTok{!=}\StringTok{ }\DecValTok{62} \OperatorTok{&}\StringTok{ }\NormalTok{PassengerId }\OperatorTok{!=}\StringTok{ }\DecValTok{830} \OperatorTok{&}\StringTok{ }\NormalTok{Pclass }\OperatorTok{==}\StringTok{ }\DecValTok{1}\NormalTok{)}
\KeywordTok{ggplot}\NormalTok{(embarked_pass_}\DecValTok{1}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Embarked, }\DataTypeTok{y =}\NormalTok{ Fare, }\DataTypeTok{fill =} \KeywordTok{factor}\NormalTok{(Pclass))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_boxplot}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{yintercept=}\DecValTok{80}\NormalTok{), }
    \DataTypeTok{colour=}\StringTok{'blue'}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{'dashed'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/Plot nulos embarked-1.pdf}

La tarifa de 80 coincide con la media de los pasajeros de primera clase
que embarcaron en C, por lo que se podría imputar este puerto.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\OperatorTok{$}\NormalTok{Embarked[}\KeywordTok{c}\NormalTok{(}\DecValTok{62}\NormalTok{, }\DecValTok{830}\NormalTok{)] <-}\StringTok{ 'C'}
\end{Highlighting}
\end{Shaded}

Otra opción, sería considerar también el sexo, ya que principios del
siglo XX, no se caracterizaba por una igualdad de hombres y mujeres.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{embarked_pass_}\DecValTok{2}\NormalTok{ <-}\StringTok{ }\NormalTok{data }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(PassengerId }\OperatorTok{!=}\StringTok{ }\DecValTok{62} \OperatorTok{&}\StringTok{ }\NormalTok{PassengerId }\OperatorTok{!=}\StringTok{ }\DecValTok{830} \OperatorTok{&}\StringTok{ }\NormalTok{Pclass }\OperatorTok{==}\StringTok{ }\DecValTok{1} \OperatorTok{&}\StringTok{ }\NormalTok{Sex }\OperatorTok{==}\StringTok{ "female"}\NormalTok{)}
\KeywordTok{ggplot}\NormalTok{(embarked_pass_}\DecValTok{2}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Embarked, }\DataTypeTok{y =}\NormalTok{ Fare, }\DataTypeTok{fill =} \KeywordTok{factor}\NormalTok{(Pclass))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_boxplot}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{yintercept=}\DecValTok{80}\NormalTok{), }
    \DataTypeTok{colour=}\StringTok{'blue'}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{'dashed'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/Plot nulos embarked considerando sexo-1.pdf}

En este caso cualquiera de los 3 puertos tendría una media cercana a 80.
Como no creemos que el puerto de embarque este correlacionado con la
supervivencia, podríamos dejar cualquiera.

Otra forma de asignar el valor de los puertos de embarque sería asignar
el valor más frequente. Calculamos cuantas veces aparece cada puerto de
embarque.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(data}\OperatorTok{$}\NormalTok{Embarked)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   C   Q   S 
## 272 123 914
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qplot}\NormalTok{(Embarked, }\DataTypeTok{data =}\NormalTok{ data,  }\DataTypeTok{fill=}\NormalTok{ Embarked) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{labs}\NormalTok{ (}\DataTypeTok{title =} \StringTok{"Distribucion Puerto de Embarque"}\NormalTok{, }
        \DataTypeTok{x=} \StringTok{"Puerto"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Cantidad"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"Puerto de embarque"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/Puertos más frecuentes de embarque-1.pdf}

Se muestra como el puerto con mayor frequencia es S, así que finalmente
asignaremos este valor.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\OperatorTok{$}\NormalTok{Embarked[}\KeywordTok{c}\NormalTok{(}\DecValTok{62}\NormalTok{, }\DecValTok{830}\NormalTok{)] <-}\StringTok{ 'S'}
\end{Highlighting}
\end{Shaded}

A continuación trataremos la variable Name, para crear una variable
Title, que nos aporte algo de información.

A partir de Name obtenemos el título de los nombres

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Mostramos algunos nombres}
\KeywordTok{head}\NormalTok{(data}\OperatorTok{$}\NormalTok{Name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Braund, Mr. Owen Harris"                            
## [2] "Cumings, Mrs. John Bradley (Florence Briggs Thayer)"
## [3] "Heikkinen, Miss. Laina"                             
## [4] "Futrelle, Mrs. Jacques Heath (Lily May Peel)"       
## [5] "Allen, Mr. William Henry"                           
## [6] "Moran, Mr. James"
\end{verbatim}

Podemos clasificar a las personas por su título.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Grab passenger title from passenger name}
\CommentTok{# Referencia:}
\CommentTok{# https://www.kaggle.com/thilakshasilva/predicting-titanic-survival-using-five-algorithms}
\NormalTok{data}\OperatorTok{$}\NormalTok{Title <-}\StringTok{ }\KeywordTok{gsub}\NormalTok{(}\StringTok{"^.*, (.*?)}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{..*$"}\NormalTok{, }\StringTok{"}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{1"}\NormalTok{, data}\OperatorTok{$}\NormalTok{Name)}
\end{Highlighting}
\end{Shaded}

Mostramos los títulos de las personas que viajaban en el Titanic

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Mostramos la variable Title en función de sex}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{table}\NormalTok{(data}\OperatorTok{$}\NormalTok{Title, data}\OperatorTok{$}\NormalTok{Sex)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{bootstrap_options =} \StringTok{"striped"}\NormalTok{, }\DataTypeTok{full_width =}\NormalTok{ F, }\DataTypeTok{position =} \StringTok{"left"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|r|r}
\hline
  & female & male\\
\hline
Capt & 0 & 1\\
\hline
Col & 0 & 4\\
\hline
Don & 0 & 1\\
\hline
Dona & 1 & 0\\
\hline
Dr & 1 & 7\\
\hline
Jonkheer & 0 & 1\\
\hline
Lady & 1 & 0\\
\hline
Major & 0 & 2\\
\hline
Master & 0 & 61\\
\hline
Miss & 260 & 0\\
\hline
Mlle & 2 & 0\\
\hline
Mme & 1 & 0\\
\hline
Mr & 0 & 757\\
\hline
Mrs & 197 & 0\\
\hline
Ms & 2 & 0\\
\hline
Rev & 0 & 8\\
\hline
Sir & 0 & 1\\
\hline
the Countess & 1 & 0\\
\hline
\end{tabular}

Podemos reasignar las ``Mlle'' (Madmoiselle) y ``Ms'' a ``Miss'',
señoritas y la ``Mme'' (Madame) a ``Mrs'' (señora). Las ocurrencias con
poca frecuencia las podemos agrupar en otros ``Other''.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Reagrupando}
\NormalTok{data}\OperatorTok{$}\NormalTok{Title[data}\OperatorTok{$}\NormalTok{Title }\OperatorTok{==}\StringTok{ 'Mlle'} \OperatorTok{|}\StringTok{ }\NormalTok{data}\OperatorTok{$}\NormalTok{Title }\OperatorTok{==}\StringTok{ 'Ms'}\NormalTok{] <-}\StringTok{ 'Miss'} 
\NormalTok{data}\OperatorTok{$}\NormalTok{Title[data}\OperatorTok{$}\NormalTok{Title }\OperatorTok{==}\StringTok{ 'Mme'}\NormalTok{]  <-}\StringTok{ 'Mrs'}
\NormalTok{Other <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'Dona'}\NormalTok{, }\StringTok{'Dr'}\NormalTok{, }\StringTok{'Lady'}\NormalTok{, }\StringTok{'the Countess'}\NormalTok{,}\StringTok{'Capt'}\NormalTok{, }\StringTok{'Col'}\NormalTok{, }\StringTok{'Don'}\NormalTok{, }\StringTok{'Jonkheer'}\NormalTok{, }\StringTok{'Major'}\NormalTok{, }\StringTok{'Rev'}\NormalTok{, }\StringTok{'Sir'}\NormalTok{)}
\NormalTok{data}\OperatorTok{$}\NormalTok{Title[data}\OperatorTok{$}\NormalTok{Title }\OperatorTok{%in%}\StringTok{ }\NormalTok{Other]  <-}\StringTok{ 'Other'}
\end{Highlighting}
\end{Shaded}

Volviendo a representarlos en función del sexo.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Mostramos el título en función del sexo}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{table}\NormalTok{(data}\OperatorTok{$}\NormalTok{Title, data}\OperatorTok{$}\NormalTok{Sex)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{bootstrap_options =} \StringTok{"striped"}\NormalTok{, }\DataTypeTok{full_width =}\NormalTok{ F, }\DataTypeTok{position =} \StringTok{"left"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|r|r}
\hline
  & female & male\\
\hline
Master & 0 & 61\\
\hline
Miss & 264 & 0\\
\hline
Mr & 0 & 757\\
\hline
Mrs & 198 & 0\\
\hline
Other & 4 & 25\\
\hline
\end{tabular}

La variable Age se podría discretizar y a partir de SibSp y Parch se
podría crear una variable con el tamaño de la familia, pero realizaremos
un modelo más sencillo, con las variables tratadas hasta ahora.

Una vez añadidos los valores faltantes, se convierten las variables
Embarked y Title a factor.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\OperatorTok{$}\NormalTok{Embarked <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(data}\OperatorTok{$}\NormalTok{Embarked)}
\NormalTok{data}\OperatorTok{$}\NormalTok{Title <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(data}\OperatorTok{$}\NormalTok{Title)}
\end{Highlighting}
\end{Shaded}

Volvemos a añadir la variable Survived y la convertimos a factor.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\OperatorTok{$}\NormalTok{Survived <-}\StringTok{ }\NormalTok{datos}\OperatorTok{$}\NormalTok{Survived}
\NormalTok{data}\OperatorTok{$}\NormalTok{Survived <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(data}\OperatorTok{$}\NormalTok{Survived)}
\end{Highlighting}
\end{Shaded}

Volvemos a mostrar la tabla con el número de valores faltantes. Recordar
que en data, no están los valores de la variable Survived.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Busco primero qué variables tienen valores perdidos}
\NormalTok{missing_numbers <-}\StringTok{ }\KeywordTok{sapply}\NormalTok{(data, }\ControlFlowTok{function}\NormalTok{(x) \{}\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(x))\})}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Variables =} \KeywordTok{names}\NormalTok{(missing_numbers), }
                 \DataTypeTok{Datos_faltantes=} \KeywordTok{as.vector}\NormalTok{(missing_numbers))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{bootstrap_options =} \StringTok{"striped"}\NormalTok{, }
                \DataTypeTok{full_width =}\NormalTok{ F, }\DataTypeTok{position =} \StringTok{"left"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|r}
\hline
Variables & Datos\_faltantes\\
\hline
PassengerId & 0\\
\hline
Pclass & 0\\
\hline
Name & 0\\
\hline
Sex & 0\\
\hline
Age & 0\\
\hline
SibSp & 0\\
\hline
Parch & 0\\
\hline
Ticket & 0\\
\hline
Fare & 0\\
\hline
Cabin & 1014\\
\hline
Embarked & 0\\
\hline
Title & 0\\
\hline
Survived & 418\\
\hline
\end{tabular}

Representamos la tabla con los tipos de los valores.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tipos_new <-}\StringTok{ }\KeywordTok{sapply}\NormalTok{(data, class)}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Variables =} \KeywordTok{names}\NormalTok{(tipos_new), }\DataTypeTok{Tipo_Variable=} \KeywordTok{as.vector}\NormalTok{(tipos_new))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{bootstrap_options =} \StringTok{"striped"}\NormalTok{, }\DataTypeTok{full_width =}\NormalTok{ F, }\DataTypeTok{position =} \StringTok{"left"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|l}
\hline
Variables & Tipo\_Variable\\
\hline
PassengerId & integer\\
\hline
Pclass & factor\\
\hline
Name & character\\
\hline
Sex & factor\\
\hline
Age & numeric\\
\hline
SibSp & integer\\
\hline
Parch & integer\\
\hline
Ticket & character\\
\hline
Fare & numeric\\
\hline
Cabin & character\\
\hline
Embarked & factor\\
\hline
Title & factor\\
\hline
Survived & factor\\
\hline
\end{tabular}

\textbf{3.2. Identificación y tratamiento de valores extremos. }

Los valores extremos tendrían sentido en los campos Fare y Age.
Procedemos al análisis de los valores extremos representando Fare y Age
con los valores extremos y sin ellos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Referencia:}
\CommentTok{# https://www.r-bloggers.com/identify-describe-plot-and-remove-the-outliers-from-the-dataset/}
\NormalTok{outlierKD <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(dt, var) \{}
\NormalTok{     var_name <-}\StringTok{ }\KeywordTok{eval}\NormalTok{(}\KeywordTok{substitute}\NormalTok{(var),}\KeywordTok{eval}\NormalTok{(dt))}
\NormalTok{     na1 <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(var_name))}
\NormalTok{     m1 <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(var_name, }\DataTypeTok{na.rm =}\NormalTok{ T)}
     \KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{), }\DataTypeTok{oma=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{0}\NormalTok{))}
     \KeywordTok{boxplot}\NormalTok{(var_name, }\DataTypeTok{main=}\StringTok{"With outliers"}\NormalTok{)}
     \KeywordTok{hist}\NormalTok{(var_name, }\DataTypeTok{main=}\StringTok{"With outliers"}\NormalTok{, }\DataTypeTok{xlab=}\OtherTok{NA}\NormalTok{, }\DataTypeTok{ylab=}\OtherTok{NA}\NormalTok{)}
\NormalTok{     outlier <-}\StringTok{ }\KeywordTok{boxplot.stats}\NormalTok{(var_name)}\OperatorTok{$}\NormalTok{out}
\NormalTok{     mo <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(outlier)}
\NormalTok{     var_name <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(var_name }\OperatorTok{%in%}\StringTok{ }\NormalTok{outlier, }\OtherTok{NA}\NormalTok{, var_name)}
     \KeywordTok{boxplot}\NormalTok{(var_name, }\DataTypeTok{main=}\StringTok{"Without outliers"}\NormalTok{)}
     \KeywordTok{hist}\NormalTok{(var_name, }\DataTypeTok{main=}\StringTok{"Without outliers"}\NormalTok{, }\DataTypeTok{xlab=}\OtherTok{NA}\NormalTok{, }\DataTypeTok{ylab=}\OtherTok{NA}\NormalTok{)}
     \KeywordTok{title}\NormalTok{(}\StringTok{"Outlier Check"}\NormalTok{, }\DataTypeTok{outer=}\OtherTok{TRUE}\NormalTok{)}
\NormalTok{     na2 <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(var_name))}
     \KeywordTok{cat}\NormalTok{(}\StringTok{"Outliers identified:"}\NormalTok{, na2 }\OperatorTok{-}\StringTok{ }\NormalTok{na1, }\StringTok{"n"}\NormalTok{)}
     \KeywordTok{cat}\NormalTok{(}\StringTok{"Propotion (%) of outliers:"}\NormalTok{, }\KeywordTok{round}\NormalTok{((na2 }\OperatorTok{-}\StringTok{ }\NormalTok{na1) }\OperatorTok{/}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(var_name))}\OperatorTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{1}\NormalTok{), }\StringTok{"n"}\NormalTok{)}
     \KeywordTok{cat}\NormalTok{(}\StringTok{"Mean of the outliers:"}\NormalTok{, }\KeywordTok{round}\NormalTok{(mo, }\DecValTok{2}\NormalTok{), }\StringTok{"n"}\NormalTok{)}
\NormalTok{     m2 <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(var_name, }\DataTypeTok{na.rm =}\NormalTok{ T)}
\NormalTok{     ###}
     \CommentTok{# cat("Mean without removing outliers:", round(m1, 2), "n")}
     \CommentTok{# cat("Mean if we remove outliers:", round(m2, 2), "n")}
     \CommentTok{# response <- readline(prompt="Do you want to remove outliers and to replace with NA? [yes/no]: ")}
     \CommentTok{# if(response == "y" | response == "yes")\{}
     \CommentTok{#      dt[as.character(substitute(var))] <- invisible(var_name)}
     \CommentTok{#      assign(as.character(as.list(match.call())$dt), dt, envir = .GlobalEnv)}
     \CommentTok{#      cat("Outliers successfully removed", "n")}
     \CommentTok{#      return(invisible(dt))}
     \CommentTok{# \} else\{}
     \CommentTok{#      cat("Nothing changed", "n")}
     \CommentTok{#      return(invisible(var_name))}
     \CommentTok{# \}}
\NormalTok{     ###}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{outlierKD}\NormalTok{(data, Age)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/Outlier 1-1.pdf}

\begin{verbatim}
## Outliers identified: 40 nPropotion (%) of outliers: 3.2 nMean of the outliers: 64.45 n
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{outlierKD}\NormalTok{(data, Fare)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/Outlier 2-1.pdf}

\begin{verbatim}
## Outliers identified: 171 nPropotion (%) of outliers: 15 nMean of the outliers: 135.25 n
\end{verbatim}

Como son perfectamente aceptables las edades y que haya gente que pagara
mucho más por su billete, al ser el primer viaje del transatlántico más
grande de la epoca, decidimos no cambiar ningún valor.

\section{4. Análisis de los datos.}\label{analisis-de-los-datos.}

\textbf{4.1. Selección de los grupos de datos que se quieren
analizar/comparar (planificación de los análisis a aplicar)}

\begin{itemize}
\tightlist
\item
  Análisis estadístico descriptivo.
\end{itemize}

Se utilizarán las variables de Edad, Clase, Género y Puerto de Embarque
para realizar el análisis de los datos.

La distribución de los pasajeros según indica el siguiente grafico.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ data) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_violin}\NormalTok{ (}\KeywordTok{aes}\NormalTok{(Pclass, Age, }\DataTypeTok{colour =} \KeywordTok{factor}\NormalTok{(Sex)),}\DataTypeTok{draw_quantiles =} \KeywordTok{c}\NormalTok{(}\FloatTok{0.25}\NormalTok{, }\FloatTok{0.5}\NormalTok{, }\FloatTok{0.75}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{ (}\DataTypeTok{title =} \StringTok{"Distribución de Pasajeros"}\NormalTok{, }\DataTypeTok{x=} \StringTok{"Clase Pasajeros"}\NormalTok{, }
        \DataTypeTok{y =} \StringTok{"Edad"}\NormalTok{ , }\DataTypeTok{colour =} \StringTok{"Género Pasajero"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-7-1.pdf}

Representando la edad de los pasajeros obtenemos:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Test_age <- na.omit(data$Age)}
\CommentTok{#Test_age <- as.integer(Test_age)}
\KeywordTok{ggplot}\NormalTok{(data,  }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Age)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{binwidth =} \DecValTok{5}\NormalTok{, }\DataTypeTok{fill =} \StringTok{'grey'}\NormalTok{, }\DataTypeTok{alpha=}\FloatTok{0.4}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_vline}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{xintercept=}\KeywordTok{median}\NormalTok{(Age, }\DataTypeTok{na.rm=}\NormalTok{T)),}
    \DataTypeTok{colour=}\StringTok{'blue'}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{'dashed'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_vline}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{xintercept=}\KeywordTok{mean}\NormalTok{(Age, }\DataTypeTok{na.rm=}\NormalTok{T)),}
  \DataTypeTok{colour=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{'dashed'}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{1}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{labs}\NormalTok{ (}\DataTypeTok{title =} \StringTok{"Distribucion Edades"}\NormalTok{, }\DataTypeTok{x=} \StringTok{"Edad"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Cantidad"}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-8-1.pdf}

Podemos observar que la media de edad de los pasajeros es de 29.8 años y
la mediana es de 28.

Finalmente realizando unos gráficos de las variables principales, clase,
sexo y puerto de embarque.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{ggplot}\NormalTok{(data,  }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Pclass)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_histogram}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill =}\NormalTok{ Pclass) ,}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{labs}\NormalTok{ (}\DataTypeTok{title =} \StringTok{"Distribución Clases"}\NormalTok{, }\DataTypeTok{x=} \StringTok{"Clase"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Cantidad"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"Clase Pasajero"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Ignoring unknown parameters: binwidth, bins, pad
\end{verbatim}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qplot}\NormalTok{(Sex, }\DataTypeTok{data =}\NormalTok{ data,  }\DataTypeTok{fill=}\NormalTok{ Sex) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{ (}\DataTypeTok{title =} \StringTok{"Distribución Género"}\NormalTok{, }\DataTypeTok{x=} \StringTok{"Género"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Cantidad"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"Género Pasajero"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-9-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qplot}\NormalTok{(Embarked, }\DataTypeTok{data =}\NormalTok{ data,  }\DataTypeTok{fill=}\NormalTok{ Embarked) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{labs}\NormalTok{ (}\DataTypeTok{title =} \StringTok{"Distribución Puerto de Embarque"}\NormalTok{, }\DataTypeTok{x=} \StringTok{"Puerto"}\NormalTok{, }
        \DataTypeTok{y =} \StringTok{"Cantidad"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"Puerto de embarque"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-9-3.pdf}

Observamos que la clase más numerosa es la 3ra clase, el sexo
predominante es el masculino y el puerto dónde hubo mayor embarque es el
de Southampton, al ser el puerto de origen del trasatlántico.

También resultará interesante, ver que grupos obtuvieron mayor
supervivencia:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Respecto a la Clase}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{filter}\NormalTok{(data, }\KeywordTok{is.na}\NormalTok{(Survived)}\OperatorTok{==}\OtherTok{FALSE}\NormalTok{), }\KeywordTok{aes}\NormalTok{(Pclass, }\DataTypeTok{fill=}\NormalTok{Survived)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(..count..)), }\DataTypeTok{alpha=}\FloatTok{0.9}\NormalTok{, }\DataTypeTok{position=}\StringTok{"dodge"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_fill_brewer}\NormalTok{(}\DataTypeTok{palette =} \StringTok{"Reds"}\NormalTok{, }\DataTypeTok{direction =} \OperatorTok{-}\DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{percent, }\DataTypeTok{breaks=}\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{0.6}\NormalTok{,}\FloatTok{0.05}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Porcentaje"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Ratio de superviviencia basado en la Clase"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{hjust =} \FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-10-1.pdf}

Representamos la supervivencia respecto al sexo.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Respecto al sexo}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{filter}\NormalTok{(data, }\KeywordTok{is.na}\NormalTok{(Survived)}\OperatorTok{==}\OtherTok{FALSE}\NormalTok{), }\KeywordTok{aes}\NormalTok{(Sex, }\DataTypeTok{fill=}\NormalTok{Survived)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(..count..)), }\DataTypeTok{alpha=}\FloatTok{0.9}\NormalTok{, }\DataTypeTok{position=}\StringTok{"dodge"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_fill_brewer}\NormalTok{(}\DataTypeTok{palette =} \StringTok{"Purples"}\NormalTok{, }\DataTypeTok{direction =} \OperatorTok{-}\DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{percent, }\DataTypeTok{breaks=}\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{0.6}\NormalTok{,}\FloatTok{0.05}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Porcentaje"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Ratio de superviviencia por Sexo"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{hjust =} \FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-1.pdf}

Representamos la supervivencia respecto al título.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Respecto al título}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{filter}\NormalTok{(data, }\KeywordTok{is.na}\NormalTok{(Survived)}\OperatorTok{==}\OtherTok{FALSE}\NormalTok{), }\KeywordTok{aes}\NormalTok{(Title, }\DataTypeTok{fill=}\NormalTok{Survived)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(..count..)), }\DataTypeTok{alpha=}\FloatTok{0.9}\NormalTok{, }\DataTypeTok{position=}\StringTok{"dodge"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_fill_brewer}\NormalTok{(}\DataTypeTok{palette =} \StringTok{"Greens"}\NormalTok{, }\DataTypeTok{direction =} \OperatorTok{-}\DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{percent, }\DataTypeTok{breaks=}\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{0.6}\NormalTok{,}\FloatTok{0.05}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Porcentaje"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Ratio de superviviencia por Título"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{hjust =} \FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-1.pdf}

\textbf{4.2. Comprobación de la normalidad y homogeneidad de la
varianza.}

Comprobar la normalidad y homogeneidad de la varianza tiene sentido para
la variables numéricas Age y Fare.

Comprobamos la normalidad, gráficamente, para Age:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Hago que los dos ejes tengan el mismo tamaño.}
\KeywordTok{ggqqplot}\NormalTok{(data}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{ggtheme =} \KeywordTok{theme}\NormalTok{(}\DataTypeTok{aspect.ratio=}\DecValTok{1}\NormalTok{), }\DataTypeTok{title =} \StringTok{"Age"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-13-1.pdf}

También se puede aplicar un test Shapiro-Wilk, en el que la hipótesis
nula, (H0) es que la muestra proviene de una población normalmente
distribuida y la hipótesis alternativa (H1), que la muestra no proviene
de una población normalmente distribuida.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Aplico el test}
\KeywordTok{shapiro.test}\NormalTok{(data}\OperatorTok{$}\NormalTok{Age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  data$Age
## W = 0.97034, p-value = 9.628e-16
\end{verbatim}

El valor de W está próximo a 1 y el p-value \textless{} 0.05, (el
p-value, debería ser p-value\textgreater{}0.05 para seguir una
distribución normal) así que se rechaza la hipótesis nula y la muestra
no sigue una distribución normal. Como se ve en la gráfica hay menos
jóvenes y más con elevada edad que habría en una distribución normal.

A continuación, comprobamos la normalidad de Fare, gráficamente:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Hago que los dos ejes tengan el mismo tamaño.}
\KeywordTok{ggqqplot}\NormalTok{(data}\OperatorTok{$}\NormalTok{Fare, }\DataTypeTok{ggtheme =} \KeywordTok{theme}\NormalTok{(}\DataTypeTok{aspect.ratio=}\DecValTok{1}\NormalTok{), }\DataTypeTok{title =} \StringTok{"Fare"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-15-1.pdf}

Aplicamos el test de Shapiro-Wilk a la variable Fare

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Aplico el test}
\KeywordTok{shapiro.test}\NormalTok{(data}\OperatorTok{$}\NormalTok{Fare)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  data$Fare
## W = 0.52765, p-value < 2.2e-16
\end{verbatim}

En este caso ni siquiera W está cercano a 1, así que se rechaza la
hipótesis nula y tampoco sigue una distribución normal.

Comprobamos la homogeneidad de la varianza, dado que hemos visto que los
datos no siguen una distribución normal, aplicaremos el test de
Fligner-Killeen.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Aplicamos el test de Fligner-Killeen.}
\KeywordTok{fligner.test}\NormalTok{(Age }\OperatorTok{~}\StringTok{ }\NormalTok{Fare, }\DataTypeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Fligner-Killeen test of homogeneity of variances
## 
## data:  Age by Fare
## Fligner-Killeen:med chi-squared = 391.77, df = 280, p-value =
## 1.132e-05
\end{verbatim}

Dado que la prueba presenta un p-valor inferior al nivel de
significancia (\textless{}0.05), se rechaza la hipótesis nula de
homocedasticidad y se concluye que la variable Age presenta una varianza
estadísticamente diferente para la distribución de Fare.

\textbf{4.3. Aplicación de pruebas estadísticas para comparar los grupos
de datos.}\\
\emph{En función de los datos y el objetivo del estudio, aplicar pruebas
de contraste de hipótesis, correlaciones, regresiones, etc.}\\
\emph{Aplicar al menos tres métodos de análisis diferentes.}

\textbf{1 - Contraste de Hipótesis}\\
\emph{Comprobar la hipótesis que la 1ra clase tiene mas posibilidades de
Sobrevivir.}

H0 : No hay diferencia significativa de sobrevivir entre la clase alta y
la clase baja.\\
H1 : La clase alta tiene mas probabilidades de sobrevivir.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Pclass_set <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(datostrain, Pclass }\OperatorTok{==}\StringTok{ }\DecValTok{1}\NormalTok{)}
\CommentTok{#function for z test}
\NormalTok{z.test =}\StringTok{ }\ControlFlowTok{function}\NormalTok{(a, b, n)\{}
\NormalTok{ sample_mean =}\StringTok{ }\KeywordTok{mean}\NormalTok{(a)}
\NormalTok{ pop_mean =}\StringTok{ }\KeywordTok{mean}\NormalTok{(b)}
\NormalTok{ c =}\StringTok{ }\KeywordTok{nrow}\NormalTok{(n)}
\NormalTok{ var_b =}\StringTok{ }\KeywordTok{var}\NormalTok{(b)}
\NormalTok{ zeta =}\StringTok{ }\NormalTok{(sample_mean }\OperatorTok{-}\StringTok{ }\NormalTok{pop_mean) }\OperatorTok{/}\StringTok{ }\NormalTok{(}\KeywordTok{sqrt}\NormalTok{(var_b}\OperatorTok{/}\NormalTok{c))}
 \KeywordTok{return}\NormalTok{(zeta)}
\NormalTok{\}}
\CommentTok{#call function}
\KeywordTok{z.test}\NormalTok{(Pclass_set}\OperatorTok{$}\NormalTok{Survived, datostrain}\OperatorTok{$}\NormalTok{Survived, Pclass_set)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.423828
\end{verbatim}

El valor de z de 7.42 afirma la hipótesis alternativa, la clase alta
tiene mas probabilidades de sobrevivir.

\textbf{2 - Correlación}\\
\emph{Comprobación de correlación entre variables}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{chisq.test}\NormalTok{(data}\OperatorTok{$}\NormalTok{Sex, data}\OperatorTok{$}\NormalTok{Pclass)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test
## 
## data:  data$Sex and data$Pclass
## X-squared = 20.379, df = 2, p-value = 3.757e-05
\end{verbatim}

Dado que el p valor es menor que 0.05, el género y la clase son
significantes y deben de tomarse en cuenta para realizar cualquier
modelo.

\textbf{3 - Regresión}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(Survived }\OperatorTok{~}\StringTok{ }\NormalTok{Age }\OperatorTok{+}\StringTok{ }\NormalTok{Pclass }\OperatorTok{+}\StringTok{ }\NormalTok{Sex }\OperatorTok{+}\StringTok{ }\NormalTok{SibSp }\OperatorTok{+}\StringTok{ }\NormalTok{Parch }\OperatorTok{+}\StringTok{ }\NormalTok{Fare }\OperatorTok{+}\StringTok{ }\NormalTok{Embarked, }
           \DataTypeTok{data =}\NormalTok{ datostrain, }\DataTypeTok{family =} \KeywordTok{binomial}\NormalTok{(}\DataTypeTok{link =} \StringTok{'logit'}\NormalTok{))}
\KeywordTok{summary}\NormalTok{(fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Survived ~ Age + Pclass + Sex + SibSp + Parch + 
##     Fare + Embarked, family = binomial(link = "logit"), data = datostrain)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7233  -0.6447  -0.3799   0.6326   2.4457  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  5.637407   0.634550   8.884  < 2e-16 ***
## Age         -0.043350   0.008232  -5.266 1.39e-07 ***
## Pclass      -1.199251   0.164619  -7.285 3.22e-13 ***
## Sexmale     -2.638476   0.222256 -11.871  < 2e-16 ***
## SibSp       -0.363208   0.129017  -2.815  0.00487 ** 
## Parch       -0.060270   0.123900  -0.486  0.62666    
## Fare         0.001432   0.002531   0.566  0.57165    
## EmbarkedQ   -0.823545   0.600229  -1.372  0.17005    
## EmbarkedS   -0.401213   0.270283  -1.484  0.13770    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 960.90  on 711  degrees of freedom
## Residual deviance: 632.34  on 703  degrees of freedom
##   (179 observations deleted due to missingness)
## AIC: 650.34
## 
## Number of Fisher Scoring iterations: 5
\end{verbatim}

Se comprueba que existe una fuerte relación entre la variable
dependiente Survived y Edad, Clase y Genero (hombre).

\section{5. Representación de los reultados a partir de tablas y
gráficas.}\label{representacion-de-los-reultados-a-partir-de-tablas-y-graficas.}

Representamos los datos de las variables.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Mostramos un histograma para cada variable cuantitativa o un gráfico de barras en caso de que}
\CommentTok{# sea una variable cualitativa.}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{2}\OperatorTok{:}\KeywordTok{ncol}\NormalTok{(data)) \{}
  \ControlFlowTok{if}\NormalTok{ (}\KeywordTok{class}\NormalTok{(data[,i]) }\OperatorTok{!=}\StringTok{ "factor"} \OperatorTok{&}\StringTok{ }\KeywordTok{class}\NormalTok{(data[,i]) }\OperatorTok{!=}\StringTok{ "character"}\NormalTok{)  \{}
    \KeywordTok{hist}\NormalTok{(data[,i], }\DataTypeTok{freq =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"steelblue"}\NormalTok{), }
         \DataTypeTok{main=}\KeywordTok{paste}\NormalTok{(}\StringTok{"Distribución de "}\NormalTok{, }
                    \KeywordTok{str_to_title}\NormalTok{(}\KeywordTok{str_replace}\NormalTok{(}\KeywordTok{colnames}\NormalTok{(data[i]), }\StringTok{"_"}\NormalTok{, }\StringTok{" "}\NormalTok{)), }\DataTypeTok{sep =} \StringTok{" "}\NormalTok{),}
         \DataTypeTok{xlab=} \KeywordTok{str_to_title}\NormalTok{(}\KeywordTok{str_replace}\NormalTok{(}\KeywordTok{colnames}\NormalTok{(data[i]), }\StringTok{"_"}\NormalTok{, }\StringTok{" "}\NormalTok{)))}
\NormalTok{  \}}
  \ControlFlowTok{else}\NormalTok{ \{}
    \ControlFlowTok{if}\NormalTok{ (}\KeywordTok{class}\NormalTok{(data[,i]) }\OperatorTok{!=}\StringTok{ "character"}\NormalTok{) \{}
      \KeywordTok{barplot}\NormalTok{(}\KeywordTok{table}\NormalTok{(data[,i]),}
            \DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"orange"}\NormalTok{,}\StringTok{"yellow"}\NormalTok{,}\StringTok{"blue"}\NormalTok{,}\StringTok{"red"}\NormalTok{),}
            \DataTypeTok{main=}\KeywordTok{paste}\NormalTok{(}\StringTok{"Distribución de "}\NormalTok{, }
                    \KeywordTok{str_to_title}\NormalTok{(}\KeywordTok{str_replace}\NormalTok{(}\KeywordTok{colnames}\NormalTok{(data[i]), }\StringTok{"_"}\NormalTok{, }\StringTok{" "}\NormalTok{)), }\DataTypeTok{sep =} \StringTok{" "}\NormalTok{),}
            \DataTypeTok{xlab=} \KeywordTok{str_to_title}\NormalTok{(}\KeywordTok{str_replace}\NormalTok{(}\KeywordTok{colnames}\NormalTok{(data[i]), }\StringTok{"_"}\NormalTok{, }\StringTok{" "}\NormalTok{)))}
\NormalTok{    \}}
\NormalTok{  \}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-21-1.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-21-2.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-21-3.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-21-4.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-21-5.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-21-6.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-21-7.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-21-8.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-21-9.pdf}

Creamos un gráfico scatter plot, para ver la correlación de las
variables:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Referencia:}
\CommentTok{# https://warwick.ac.uk/fac/sci/moac/people/students/peter_cock/r/iris_plots/}
\CommentTok{# Función para mostrar la correlación}
\NormalTok{panel.pearson <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x, y, ...) \{}
\NormalTok{horizontal <-}\StringTok{ }\NormalTok{(}\KeywordTok{par}\NormalTok{(}\StringTok{"usr"}\NormalTok{)[}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\KeywordTok{par}\NormalTok{(}\StringTok{"usr"}\NormalTok{)[}\DecValTok{2}\NormalTok{]) }\OperatorTok{/}\StringTok{ }\DecValTok{2}\NormalTok{;}
\NormalTok{vertical <-}\StringTok{ }\NormalTok{(}\KeywordTok{par}\NormalTok{(}\StringTok{"usr"}\NormalTok{)[}\DecValTok{3}\NormalTok{] }\OperatorTok{+}\StringTok{ }\KeywordTok{par}\NormalTok{(}\StringTok{"usr"}\NormalTok{)[}\DecValTok{4}\NormalTok{]) }\OperatorTok{/}\StringTok{ }\DecValTok{2}\NormalTok{;}
\KeywordTok{text}\NormalTok{(horizontal, vertical, }\KeywordTok{format}\NormalTok{(}\KeywordTok{abs}\NormalTok{(}\KeywordTok{cor}\NormalTok{(x,y)), }\DataTypeTok{digits=}\DecValTok{2}\NormalTok{))}
\NormalTok{\}}
\CommentTok{# Gráfico de parejas}
\KeywordTok{pairs}\NormalTok{(data[}\KeywordTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{9}\NormalTok{)], }\DataTypeTok{main =} \StringTok{"Data plot en función de las clases"}\NormalTok{, }\DataTypeTok{pch =} \KeywordTok{c}\NormalTok{(}\DecValTok{22}\NormalTok{,}\DecValTok{23}\NormalTok{,}\DecValTok{24}\NormalTok{,}\DecValTok{25}\NormalTok{),}
      \DataTypeTok{bg =} \KeywordTok{c}\NormalTok{(}\StringTok{"yellow"}\NormalTok{,}\StringTok{"blue"}\NormalTok{,}\StringTok{"red"}\NormalTok{) [}\KeywordTok{unclass}\NormalTok{(data[,}\StringTok{'Pclass'}\NormalTok{])],}
      \DataTypeTok{upper.panel =}\NormalTok{ panel.pearson)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-22-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Referencia:}
\CommentTok{# https://warwick.ac.uk/fac/sci/moac/people/students/peter_cock/r/iris_plots/}
\CommentTok{# Función para mostrar la correlación}
\NormalTok{panel.pearson <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x, y, ...) \{}
\NormalTok{horizontal <-}\StringTok{ }\NormalTok{(}\KeywordTok{par}\NormalTok{(}\StringTok{"usr"}\NormalTok{)[}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\KeywordTok{par}\NormalTok{(}\StringTok{"usr"}\NormalTok{)[}\DecValTok{2}\NormalTok{]) }\OperatorTok{/}\StringTok{ }\DecValTok{2}\NormalTok{;}
\NormalTok{vertical <-}\StringTok{ }\NormalTok{(}\KeywordTok{par}\NormalTok{(}\StringTok{"usr"}\NormalTok{)[}\DecValTok{3}\NormalTok{] }\OperatorTok{+}\StringTok{ }\KeywordTok{par}\NormalTok{(}\StringTok{"usr"}\NormalTok{)[}\DecValTok{4}\NormalTok{]) }\OperatorTok{/}\StringTok{ }\DecValTok{2}\NormalTok{;}
\KeywordTok{text}\NormalTok{(horizontal, vertical, }\KeywordTok{format}\NormalTok{(}\KeywordTok{abs}\NormalTok{(}\KeywordTok{cor}\NormalTok{(x,y)), }\DataTypeTok{digits=}\DecValTok{2}\NormalTok{))}
\NormalTok{\}}
\CommentTok{# Gráfico de parejas}
\KeywordTok{pairs}\NormalTok{(data[}\KeywordTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{9}\NormalTok{)], }\DataTypeTok{main =} \StringTok{"Data plot en función del sexo"}\NormalTok{, }\DataTypeTok{pch =} \KeywordTok{c}\NormalTok{(}\DecValTok{22}\NormalTok{,}\DecValTok{23}\NormalTok{,}\DecValTok{24}\NormalTok{,}\DecValTok{25}\NormalTok{),}
      \DataTypeTok{bg =} \KeywordTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{,}\StringTok{"red"}\NormalTok{) [}\KeywordTok{unclass}\NormalTok{(data[,}\StringTok{'Sex'}\NormalTok{])],}
      \DataTypeTok{upper.panel =}\NormalTok{ panel.pearson)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-23-1.pdf}

Antes de pasar a la resolución del problema en sí, de predecir la
variable Survived en el conjunto de test, podemos guardar los resultados
de los conjuntos de datos tratados.

Para ello, volvemos a separar los datos, tomando sólo las columnas que
utilizaremos para la predicción. No se utilizan los datos de Cabin ni de
Ticket. Los datos de Name, se han tratado y sustituido por Title.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Referencia}
\CommentTok{# https://www.kaggle.com/thilakshasilva/predicting-titanic-survival-using-five-algorithms#exploratory-data-analysis}
\CommentTok{# Volvemos a partir el conjunto de datos}
\NormalTok{titanic_train <-}\StringTok{ }\NormalTok{data[}\DecValTok{1}\OperatorTok{:}\DecValTok{891}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{"Survived"}\NormalTok{,}\StringTok{"Pclass"}\NormalTok{,}\StringTok{"Sex"}\NormalTok{,}\StringTok{"Age"}\NormalTok{,}\StringTok{"SibSp"}\NormalTok{,}\StringTok{"Parch"}\NormalTok{,}\StringTok{"Fare"}\NormalTok{,}\StringTok{"Embarked"}\NormalTok{,}\StringTok{"Title"}\NormalTok{)]}
\NormalTok{titanic_test <-}\StringTok{ }\NormalTok{data[}\DecValTok{892}\OperatorTok{:}\DecValTok{1309}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{"Pclass"}\NormalTok{,}\StringTok{"Sex"}\NormalTok{,}\StringTok{"Age"}\NormalTok{,}\StringTok{"SibSp"}\NormalTok{,}\StringTok{"Parch"}\NormalTok{,}\StringTok{"Fare"}\NormalTok{,}\StringTok{"Embarked"}\NormalTok{,}\StringTok{"Title"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

Y guardamos los archivos:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Guardamos el archivo}
\KeywordTok{write.csv}\NormalTok{(titanic_train, }\DataTypeTok{file =} \StringTok{'./output/titanic_train_treated.csv'}\NormalTok{, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{quote=}\OtherTok{FALSE}\NormalTok{)}
\KeywordTok{write.csv}\NormalTok{(titanic_test, }\DataTypeTok{file =} \StringTok{'./output/titanic_test_treated.csv'}\NormalTok{, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{quote=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{6. Resolución del problema.}\label{resolucion-del-problema.}

\textbf{A partir de los resultados obtenidos. ¿cuáles son las
conclusiones?. ¿Los resultados permiten responder al problema?}

Como se trata de predecir una variable binaria, podemos crear un modelo
de regresión logística que sea función de las otras variables.

Utilizaremos una parte del conjunto de train del que conocemos los
resultados, para validar los resultados.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Volvemos a partir el conjunto de datos}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{198}\NormalTok{)}
\NormalTok{particion =}\StringTok{ }\KeywordTok{sample.split}\NormalTok{(titanic_train}\OperatorTok{$}\NormalTok{Survived, }\DataTypeTok{SplitRatio =} \FloatTok{0.8}\NormalTok{)}
\NormalTok{train =}\StringTok{ }\KeywordTok{subset}\NormalTok{(titanic_train, particion }\OperatorTok{==}\StringTok{ }\OtherTok{TRUE}\NormalTok{)}
\NormalTok{test =}\StringTok{ }\KeywordTok{subset}\NormalTok{(titanic_train, particion }\OperatorTok{==}\StringTok{ }\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Referencia:}
\CommentTok{# https://rpubs.com/emilopezcano/logit}
\CommentTok{# Modelo de regresión logística}
\NormalTok{titanic.logit <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(Survived }\OperatorTok{~}\StringTok{ }\NormalTok{Pclass }\OperatorTok{+}\StringTok{ }\NormalTok{Sex }\OperatorTok{+}\StringTok{ }\NormalTok{Age }\OperatorTok{+}\StringTok{ }\NormalTok{SibSp }\OperatorTok{+}\StringTok{ }\NormalTok{Parch }\OperatorTok{+}\StringTok{ }\NormalTok{Fare }\OperatorTok{+}\StringTok{ }\NormalTok{Embarked }\OperatorTok{+}\StringTok{ }\NormalTok{Title,}
                    \DataTypeTok{data =}\NormalTok{ titanic_train, }\DataTypeTok{family =} \StringTok{"binomial"}\NormalTok{(}\DataTypeTok{link=}\StringTok{"logit"}\NormalTok{))}
\KeywordTok{summary}\NormalTok{(titanic.logit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Survived ~ Pclass + Sex + Age + SibSp + Parch + 
##     Fare + Embarked + Title, family = binomial(link = "logit"), 
##     data = titanic_train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3878  -0.5480  -0.3801   0.5353   2.5499  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  19.665733 504.958265   0.039 0.968934    
## Pclass2      -1.130844   0.330031  -3.426 0.000611 ***
## Pclass3      -2.243296   0.331563  -6.766 1.33e-11 ***
## Sexmale     -15.212933 504.957877  -0.030 0.975966    
## Age          -0.028446   0.009691  -2.935 0.003331 ** 
## SibSp        -0.569158   0.126612  -4.495 6.95e-06 ***
## Parch        -0.361322   0.135575  -2.665 0.007697 ** 
## Fare          0.003362   0.002653   1.267 0.205055    
## EmbarkedQ    -0.071733   0.395059  -0.182 0.855916    
## EmbarkedS    -0.408573   0.251683  -1.623 0.104512    
## TitleMiss   -15.772521 504.958131  -0.031 0.975082    
## TitleMr      -3.508822   0.540508  -6.492 8.49e-11 ***
## TitleMrs    -14.972348 504.958197  -0.030 0.976346    
## TitleOther   -3.543153   0.781496  -4.534 5.79e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1186.66  on 890  degrees of freedom
## Residual deviance:  724.73  on 877  degrees of freedom
## AIC: 752.73
## 
## Number of Fisher Scoring iterations: 13
\end{verbatim}

Vemos como hay variables que no tienen tanta importancia en el
clasificador como Sex y Embarked. Aplicamos la función step para ir
quitando estas variables que no tienen tanta importancia.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Modelo de regresión logística}
\NormalTok{titanic.logit <-}\StringTok{ }\KeywordTok{step}\NormalTok{(titanic.logit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=752.73
## Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked + 
##     Title
## 
##            Df Deviance    AIC
## - Embarked  2   727.94 751.94
## - Fare      1   726.55 752.55
## <none>          724.73 752.73
## - Sex       1   730.19 756.19
## - Parch     1   732.36 758.36
## - Age       1   733.75 759.75
## - SibSp     1   750.31 776.31
## - Pclass    2   774.74 798.74
## - Title     4   782.95 802.95
## 
## Step:  AIC=751.94
## Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Title
## 
##          Df Deviance    AIC
## <none>        727.94 751.94
## - Fare    1   730.69 752.69
## - Sex     1   733.31 755.31
## - Parch   1   736.27 758.27
## - Age     1   737.68 759.68
## - SibSp   1   756.65 778.65
## - Pclass  2   780.00 800.00
## - Title   4   786.70 802.70
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Modelo de regresión logística}
\KeywordTok{summary}\NormalTok{(titanic.logit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Survived ~ Pclass + Sex + Age + SibSp + Parch + 
##     Fare + Title, family = binomial(link = "logit"), data = titanic_train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.4621  -0.5405  -0.3886   0.5325   2.6471  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  19.410542 498.876533   0.039 0.968963    
## Pclass2      -1.223069   0.324793  -3.766 0.000166 ***
## Pclass3      -2.248701   0.321985  -6.984 2.87e-12 ***
## Sexmale     -15.189027 498.876155  -0.030 0.975711    
## Age          -0.029122   0.009569  -3.043 0.002340 ** 
## SibSp        -0.593281   0.125619  -4.723 2.33e-06 ***
## Parch        -0.373677   0.134520  -2.778 0.005472 ** 
## Fare          0.004043   0.002633   1.535 0.124694    
## TitleMiss   -15.741626 498.876416  -0.032 0.974828    
## TitleMr      -3.554349   0.537396  -6.614 3.74e-11 ***
## TitleMrs    -14.973049 498.876481  -0.030 0.976056    
## TitleOther   -3.514816   0.775871  -4.530 5.89e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1186.66  on 890  degrees of freedom
## Residual deviance:  727.94  on 879  degrees of freedom
## AIC: 751.94
## 
## Number of Fisher Scoring iterations: 13
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Modelo de regresión logística}
\NormalTok{titanic.logit <-}\StringTok{ }\KeywordTok{step}\NormalTok{(titanic.logit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=751.94
## Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Title
## 
##          Df Deviance    AIC
## <none>        727.94 751.94
## - Fare    1   730.69 752.69
## - Sex     1   733.31 755.31
## - Parch   1   736.27 758.27
## - Age     1   737.68 759.68
## - SibSp   1   756.65 778.65
## - Pclass  2   780.00 800.00
## - Title   4   786.70 802.70
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Modelo de regresión logística}
\KeywordTok{vif}\NormalTok{(titanic.logit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                GVIF Df GVIF^(1/(2*Df))
## Pclass 2.169085e+00  2        1.213582
## Sex    6.818832e+06  1     2611.289253
## Age    1.991458e+00  1        1.411190
## SibSp  1.614081e+00  1        1.270465
## Parch  1.458854e+00  1        1.207830
## Fare   1.586248e+00  1        1.259464
## Title  1.492792e+07  4        7.884060
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Modelo de regresión logística}
\KeywordTok{durbinWatsonTest}\NormalTok{(titanic.logit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  lag Autocorrelation D-W Statistic p-value
##    1       0.0204161      1.958783   0.568
##  Alternative hypothesis: rho != 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Comprobamos los resultados en el conjunto de test de validación}
\NormalTok{prob_pred =}\StringTok{ }\KeywordTok{predict}\NormalTok{(titanic.logit, }\DataTypeTok{type =} \StringTok{'response'}\NormalTok{, }\DataTypeTok{newdata =}\NormalTok{ test)}
\NormalTok{y_pred =}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(prob_pred }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\KeywordTok{head}\NormalTok{(y_pred)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  1  2 12 13 16 22 
##  0  1  1  0  1  0
\end{verbatim}

Comprobamos la matriz de confusion

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Comprobamos la matriz de confusión}
\KeywordTok{table}\NormalTok{(test}\OperatorTok{$}\NormalTok{Survived, y_pred }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
##     FALSE TRUE
##   0    97   13
##   1    17   51
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#kable(table(test$Survived, (y_pred > 0.5)) %>%}
\CommentTok{#  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")}
\end{Highlighting}
\end{Shaded}

Calculamos la precisión del modelo.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{error <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(test}\OperatorTok{$}\NormalTok{Survived }\OperatorTok{!=}\StringTok{ }\NormalTok{y_pred) }\CommentTok{# Misclassification error}
\KeywordTok{paste}\NormalTok{(}\StringTok{'Accuracy'}\NormalTok{,}\KeywordTok{round}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{error,}\DecValTok{4}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Accuracy 0.8315"
\end{verbatim}

Finalmente, calculamos los valores finales

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Calculamos las predicciones}
\NormalTok{titanic_prob =}\StringTok{ }\KeywordTok{predict}\NormalTok{(titanic.logit, }\DataTypeTok{newdata =}\NormalTok{ titanic_test)}
\NormalTok{titanic_pred =}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(titanic_prob }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Guardamos los resultados}
\NormalTok{results <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{PassengerID =}\NormalTok{ data[}\DecValTok{892}\OperatorTok{:}\DecValTok{1309}\NormalTok{,}\StringTok{"PassengerId"}\NormalTok{], }\DataTypeTok{Survived =}\NormalTok{ titanic_pred)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Guardamos el archivo}
\KeywordTok{write.csv}\NormalTok{(results, }\DataTypeTok{file =} \StringTok{'./output/PrediccionSupervivenciaTitanic.csv'}\NormalTok{, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{quote=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{7. Código. Hay que adjuntar el código, preferiblemente en R,
con el que se ha realizado la limpieza, análisis y represntación de los
datos.}\label{codigo.-hay-que-adjuntar-el-codigo-preferiblemente-en-r-con-el-que-se-ha-realizado-la-limpieza-analisis-y-represntacion-de-los-datos.}

El código está integrado en el documento .Rmd y sale convenientemente
formateado cuando se exporta por Knit en .html o .pdf.

Participación de los integrantes del equipo:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Creamos una tabla en formato kagle para mostrar la participación:}
\NormalTok{participantes <-}\StringTok{  }\KeywordTok{c}\NormalTok{(}\StringTok{"Investigación previa"}\NormalTok{, }\StringTok{"L.G, J.L.M."}\NormalTok{, }
                    \StringTok{"Redacción de las respuestas"}\NormalTok{, }\StringTok{"L.G, J.L.M."}\NormalTok{, }
                    \StringTok{"Desarrollo código", "}\NormalTok{L.G, J.L.M.}\StringTok{")}
\StringTok{df <- matrix(participantes, ncol = 2, byrow = TRUE) }
\StringTok{colnames(df) <- c("}\NormalTok{Contribuciones}\StringTok{", "}\NormalTok{Firmas}\StringTok{") }
\StringTok{kable(df) %>%}
\StringTok{  kable_styling(bootstrap_options = "}\NormalTok{striped}\StringTok{", full_width = F, position = "}\NormalTok{left}\StringTok{")}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|l}
\hline
Contribuciones & Firmas\\
\hline
Investigación previa & L.G, J.L.M.\\
\hline
Redacción de las respuestas & L.G, J.L.M.\\
\hline
Desarrollo código & L.G, J.L.M.\\
\hline
\end{tabular}

\section*{8. Bibliografía.}\label{bibliografia.}
\addcontentsline{toc}{section}{8. Bibliografía.}

\hypertarget{refs}{}
\hypertarget{ref-baayen2008analyzing}{}
Baayen, R Harald. 2008. \emph{Analyzing Linguistic Data: A Practical
Introduction to Statistics Using R}. Cambridge University Press.

\hypertarget{ref-calvointroduccionlimpieza}{}
Calvo, Laia; Pérez, Mireia; Subirats. 2019. \emph{Introducción a La
Limpieza Y Análisis de Los Datos}. Universitat Oberta de Catalunya, UOC.

\hypertarget{ref-gibergansregresionsimple}{}
Gibergans Bàquena, J. 2009. \emph{Regresión Lineal Simple}. Universitat
Oberta de Catalunya, UOC.

\hypertarget{ref-gibergansregresionmultiple}{}
Gibergans Bàquena, Josep. 2009. \emph{Regresión Lineal Múltiple}.
Universitat Oberta de Catalunya, UOC.

\hypertarget{ref-gibergansregresionmuxfaltiple}{}
Gillén Estany, Montserrat. 2017. \emph{Modelización Predictiva:
Introducción a Los Modelos Lineales Generalizados}. Universitat Oberta
de Catalunya, UOC.

\hypertarget{ref-hothorn2014handbook}{}
Hothorn, Torsten, and Brian S Everitt. 2014. \emph{A Handbook of
Statistical Analyses Using R}. CRC press.

\hypertarget{ref-rpubsemilio}{}
\emph{Https://Rpubs.com/Emilopezcano/Logit}. Accedido 02/06/2019.

\hypertarget{ref-sthda}{}
\emph{Https://Www.kaggle.com/c/Titanic}. Accedido 01/06/2019.

\hypertarget{ref-kaggle}{}
\emph{Https://Www.kaggle.com/Thilakshasilva/Predicting-Titanic-Survival-Using-Five-Algorithms\#exploratory-Data-Analysis}.
Accedido 01/06/2019.

\hypertarget{ref-teetor2011r}{}
Teetor, Paul. 2011. \emph{R Cookbook: Proven Recipes for Data Analysis,
Statistics, and Graphics}. `` O'Reilly Media, Inc.''

\hypertarget{ref-vegaspreprocesamiento}{}
Vegas Lozano, Esteban. \emph{Preprocesamiento de Los Datos}. Universitat
Oberta de Catalunya, UOC.


\end{document}
